import os

from dotenv import load_dotenv
from flask import Flask, render_template, request, redirect, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import URL, text
from sqlalchemy.exc import IntegrityError, OperationalError

# Load the database settings from .env
load_dotenv()

# Create the Flask website
app = Flask(__name__)

#allow the application to update while the server is running
app.config["DEBUG"] = True

#flash the secret key to secure sessions
app.config['SECRET_KEY'] = 'your secret key'

# Tell SQLAlchemy which database to connect to
# URL.create handles special characters in the password correctly
app.config["SQLALCHEMY_DATABASE_URI"] = URL.create(
    drivername="mysql+pymysql",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME")
)

# Use the Aiven certificate to verify the database server
app.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
    "connect_args": {
        "ssl_ca": os.getenv("DB_SSL_CA"),
        "ssl_verify_cert": True,
        "ssl_verify_identity": True
    }
}

# Set up SQLAlchemy for this Flask app
db = SQLAlchemy(app)

# Check that it can connect when the app starts, and prevent crash if connection times out
try:
    with app.app_context():
        with db.engine.connect() as connection:
            result = connection.execute(text("SELECT DATABASE();"))
            print("Connected to database:", result.scalar())

except OperationalError:
    raise SystemExit("Database connection failed. Stopping app.")

# -----------------------------------
# ----------DATABASE MODELS----------
# -----------------------------------

# Describe the existing employee table so SQLAlchemy can use it
class Employee(db.Model):
    __tablename__ = "employee"

    # Unique ID generated by MySQL for each employee
    employee_id = db.Column(db.Integer, primary_key=True)

    # Basic employee information
    name = db.Column(db.String(150), nullable=False)
    email = db.Column(db.String(254), unique=True, nullable=False)
    phone_number = db.Column(db.String(30))
    job_title = db.Column(db.String(100), nullable=False)

    # Non-admin employees can have no password hash
    password_hash = db.Column(db.String(255))

    # Track employment status and permission to log in
    active = db.Column(db.Boolean, nullable=False, default=True)
    admin = db.Column(db.Boolean, nullable=False, default=False)


# Show the login page when someone first opens the website
@app.route("/", methods=["GET", "POST"])
@app.route("/login", methods=["GET", "POST"])
def login():
    # Temporarily send every submitted login directly to the dashboard
    # Authentication will be added later
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
    
        mydb = db.engine.raw_connection() # Connect to database using sqlalchemy
        cursor = mydb.cursor()
        query = "SELECT * FROM employee WHERE email = %s AND password_hash = %s AND admin = True ;"
        cursor.execute(query, (username, password))
        admin = cursor.fetchone()

        mydb.close()
        if admin: 
            flash('Login successful!', 'success')
            return redirect(url_for('dashboard'))
        else:
            flash('Invalid credentials. Please try again.', 'error')
            return render_template('login')
        
    return render_template('login.html')


# Display the dashboard page
@app.route("/dashboard")
def dashboard():
    return render_template("dashboard.html")


# Read all employees and display them alphabetically by name.
@app.route("/employees")
def employees():
    employee_list = db.session.execute(
        db.select(Employee).order_by(Employee.name)
    ).scalars().all()

    return render_template("employees.html", employees=employee_list)

@app.route("/employees/add", methods=["GET", "POST"])
def add_employee():
    error = None

    if request.method == "POST":
        # Read the submitted values and remove extra spaces
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip()
        phone = request.form.get("phone_number", "").strip()
        job_title = request.form.get("job_title", "").strip()

        # Make sure the required fields contain text
        if not name or not email or not job_title:
            error = "Name, email, and job title are required."

        else:
            # Build an employee record from the form values
            employee = Employee(
                name=name,
                email=email,
                phone_number=phone or None,
                job_title=job_title,
                active=True,
                admin=False,
                password_hash=None
            )

            try:
                # Save the new employee to the database
                db.session.add(employee)
                db.session.commit()

            except IntegrityError:
                # Reset the session when MySQL rejects the insert
                db.session.rollback()
                error = "Could not save. That email may already be in use."

            else:
                # Reload the employee list after a successful save
                return redirect(url_for("employees"))

    # Display the form, including an error if saving failed
    return render_template("add_employee.html", error=error)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5001, debug=True)